ssh:
  user: root
  pass: password

load:
  100:
    heavy:
      ratio: 5
      conn: 8
    medium:
      ratio: 5
      conn: 4
    lite:
      ratio: 10
      conn: 2
  250:
    heavy:
      ratio: 30
      conn: 40
    medium:
      ratio: 30
      conn: 20
    lite:
      ratio: 20
      conn: 10

output_dir: /var/vcap/data/density_test/logs
local_db_dir: /root/work/tangrui/mega_test/local_db
nats: nats://foo:bar@10.1.1.3:4222
nodes:
  redis_node_100_0: 10.1.1.1
  redis_node_200_0: 10.1.1.2
